### ISSUE TITLE
Wrong description in __init__.py

### ISSUE THREAD

**Issue by tobytteh** [sopel-irc/sopel-imdb#4]
In https://github.com/RustyBower/sopel-imdb/blob/master/sopel_modules/imdb/__init__.py#L3

It says: `A working re-implementation of the weather module for Sopel`

Just something I noticed!

**Comment by RustyBower** [comment]
Fixed in https://github.com/RustyBower/sopel-imdb/commit/13ae69b37e3747646b1b7a42136774c5c42df6f1
