### ISSUE TITLE
Letterboxd

### ISSUE THREAD

**Issue by PanderMusubi** [sopel-irc/sopel-imdb#9]
If possible, please create a module that offers similar functionality for Letterboxd.

**Comment by RustyBower** [comment]
Scrolling through real quick, it looks like Letterboxd is similar to Trakt, but apparently only offers movies?

Can you give me some example output you'd want to see out of the plugin?

**Comment by PanderMusubi** [comment]
I don't know Trakt. I do know it is build on themoviedb.org and will support the TV shows that are in there in a while. Example output for `.letterboxd ghostbusters` or `.lbd ghostbusters` would be

    [Movie] Title: Ghostbusters | Year: 1984 | Rating: 3.8 | Watched: 442K | Likes: 102K | Lists: 45K | Fans: 2.5K | Genres: Fantasy, Comedy | Tagline: They ain’t afraid of no ghost. | Letterboxd Link: https://letterboxd.com/film/ghostbusters/

**Comment by dgw** [comment]
I'm not able to find anything about Letterboxd expanding support for TV shows. Their [FAQ entry about TV](https://letterboxd.com/about/frequent-questions/?s=support+tv+shows) says:

> ### Do you support TV shows?
> No, we do not support ‘returning’ TV shows. For historic reasons, we support a small selection of television content that was originally [allowed by TMDb](https://www.themoviedb.org/documentation/editing#television) in its Movies section (limited or miniseries, TV movies) as well as some notable exceptions like _Black Mirror_ episodes and shows that were initially marketed as limited series but subsequently given second seasons (like _Big Little Lies_). TMDb has since moved this content to a new TV section; as a result, some films on Letterboxd link to TV entries instead of movies (so that we continue to receive content updates).
>
> We reserve the right to remove television-related content from our service at any time.

The only recent Twitter reply I could find about TV (that wasn't just a link to the above FAQ entry) was [this](https://twitter.com/letterboxd/status/1369389195832270851), which makes no promises:

> Hi there, @&#8203;goodreads is available for books. As for TV, it's definitely a popular request. No plans yet but we never say never!

Honestly I like the idea of making a Trakt plugin, but obviously there's a whole other community around Letterboxd. We could have both eventually. I'd just say that someone who _uses_ Letterboxd would be the best candidate for running development on a plugin. That's not me (I use Trakt), and it's not Rusty.

Even if you can't contribute _code_, @PanderMusubi, would you stay involved with bug reports and feature ideas after the basic plugin is written? It's ideal to have someone with an ear to the ground, so to speak, in case Letterboxd announces changes that will affect the plugin.

**Comment by RustyBower** [comment]
Closing this in favor of https://github.com/sopel-irc/sopel-letterboxd/issues/1
